### ISSUE TITLE
unauthorized app

### ISSUE THREAD

**Issue by HenryColey** [markovic-nikola/pubg-recoil#2]
i trying to install this, but i got unauthorized app message. how to resolve ?

**Comment by markovic-nikola** [comment]
You need to be whitelisted as developer by Overwolf staff in order to load unpackaged apps.
Anyway they will release the app to the app store tomorrow so you can check it there as well.

**Comment by markovic-nikola** [comment]
https://www.overwolf.com/app/Nikola_Markovic-PUBG_Recoil
